server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: VYzk3y3TYLqqhULzaoMJZrLY2sSfnKwH
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/gateway"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
          user-name-attribute: preferred_username
          jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
